DROP TABLE IF EXISTS escolas;

CREATE TABLE escolas (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    CO_ENTIDADE INTEGER,
    NO_ENTIDADE TEXT,
    CO_UF INTEGER,
    CO_MUNICIPIO INTEGER,
    QT_MAT_BAS INTEGER,
    QT_MAT_INF INTEGER,
    QT_MAT_FUND INTEGER,
    QT_MAT_MED INTEGER,
    QT_MAT_PROF INTEGER,
    QT_MAT_EJA INTEGER,
    QT_MAT_ESP INTEGER
);
